export default {
    composer_requirements: {
        package: 'string',
        version: 'string',
        other_package: 'string',
        constraint: 'string',
    },
    extensions: {
        package: 'string',
        flarumid: 'string',
        repository: 'string',
        abandoned: 'string',
        github_stars: 'uint',
        github_watchers: 'uint',
        github_forks: 'uint',
        github_open_issues: 'uint',
        downloads_total: 'uint',
        downloads_monthly: 'uint',
        downloads_daily: 'uint',
    },
    issues: {
        package: 'string',
        version: 'string',
        file: 'string',
        description: 'string',
    },
    javascript_imports: {
        package: 'string',
        version: 'string',
        file: 'string',
        class: 'string',
    },
    javascript_initializers: {
        package: 'string',
        version: 'string',
        file: 'string',
        key: 'string',
    },
    language_packs: {
        package: 'string',
        version: 'string',
        locale: 'string',
        key: 'title',
    },
    php_imports: {
        package: 'string',
        version: 'string',
        file: 'string',
        class: 'string',
    },
    releases: {
        package: 'string',
        version: 'string',
        license: 'string',
        title: 'string',
        description: 'string',
        icon_name: 'string',
        icon_image: 'string',
        icon_color: 'string',
        icon_background: 'string',
        discuss: 'string',
        date: 'date',
    },
    route_definitions: {
        package: 'string',
        version: 'string',
        file: 'string',
        method: 'string',
        path: 'string',
    },
    translation_definitions: {
        package: 'string',
        version: 'string',
        locale: 'string',
        key: 'string',
        value: 'string',
    },
    translation_usages: {
        package: 'string',
        version: 'string',
        file: 'string',
        key: 'string',
    },
};
